//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.23 at 03:33:13 PM PST 
//


package com.aladdin.aqs.coldboot.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="caches">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="cache" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="coldboot-query" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="gpx" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "caches"
})
@XmlRootElement(name = "coldboot-policy")
public class ColdbootPolicy {

    @XmlElement(required = true)
    protected ColdbootPolicy.Caches caches;

    /**
     * Gets the value of the caches property.
     * 
     * @return
     *     possible object is
     *     {@link ColdbootPolicy.Caches }
     *     
     */
    public ColdbootPolicy.Caches getCaches() {
        return caches;
    }

    /**
     * Sets the value of the caches property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColdbootPolicy.Caches }
     *     
     */
    public void setCaches(ColdbootPolicy.Caches value) {
        this.caches = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="cache" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="coldboot-query" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="gpx" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cache"
    })
    public static class Caches {

        protected List<ColdbootPolicy.Caches.Cache> cache;

        /**
         * Gets the value of the cache property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cache property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCache().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ColdbootPolicy.Caches.Cache }
         * 
         * 
         */
        public List<ColdbootPolicy.Caches.Cache> getCache() {
            if (cache == null) {
                cache = new ArrayList<ColdbootPolicy.Caches.Cache>();
            }
            return this.cache;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="coldboot-query" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="gpx" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Cache {

            @XmlAttribute(name = "class")
            protected String clazz;
            @XmlAttribute(name = "package")
            protected String _package;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "coldboot-query")
            protected String coldbootQuery;
            @XmlAttribute(name = "gpx")
            protected Boolean gpx;

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

            /**
             * Gets the value of the package property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPackage() {
                return _package;
            }

            /**
             * Sets the value of the package property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPackage(String value) {
                this._package = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the coldbootQuery property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColdbootQuery() {
                return coldbootQuery;
            }

            /**
             * Sets the value of the coldbootQuery property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColdbootQuery(String value) {
                this.coldbootQuery = value;
            }

            /**
             * Gets the value of the gpx property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isGpx() {
                if (gpx == null) {
                    return false;
                } else {
                    return gpx;
                }
            }

            /**
             * Sets the value of the gpx property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setGpx(Boolean value) {
                this.gpx = value;
            }

        }

    }

}
