//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 10:39:34 AM PST 
//


package com.aladdin.sybase.schema.mapper.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aladdin.sybase.schema.mapper.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aladdin.sybase.schema.mapper.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SchemaMapping }
     * 
     */
    public SchemaMapping createSchemaMapping() {
        return new SchemaMapping();
    }

    /**
     * Create an instance of {@link SchemaMapping.Sybase }
     * 
     */
    public SchemaMapping.Sybase createSchemaMappingSybase() {
        return new SchemaMapping.Sybase();
    }

    /**
     * Create an instance of {@link SchemaMapping.Sybase.Databases }
     * 
     */
    public SchemaMapping.Sybase.Databases createSchemaMappingSybaseDatabases() {
        return new SchemaMapping.Sybase.Databases();
    }

    /**
     * Create an instance of {@link SchemaMapping.Sybase.Databases.Database }
     * 
     */
    public SchemaMapping.Sybase.Databases.Database createSchemaMappingSybaseDatabasesDatabase() {
        return new SchemaMapping.Sybase.Databases.Database();
    }

    /**
     * Create an instance of {@link SchemaMapping.Sybase.Databases.Database.Tables }
     * 
     */
    public SchemaMapping.Sybase.Databases.Database.Tables createSchemaMappingSybaseDatabasesDatabaseTables() {
        return new SchemaMapping.Sybase.Databases.Database.Tables();
    }

    /**
     * Create an instance of {@link SchemaMapping.Sybase.Databases.Database.Tables.Table }
     * 
     */
    public SchemaMapping.Sybase.Databases.Database.Tables.Table createSchemaMappingSybaseDatabasesDatabaseTablesTable() {
        return new SchemaMapping.Sybase.Databases.Database.Tables.Table();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link SchemaMapping.Sybase.Databases.Database.Tables.Table.ExcludedColumns }
     * 
     */
    public SchemaMapping.Sybase.Databases.Database.Tables.Table.ExcludedColumns createSchemaMappingSybaseDatabasesDatabaseTablesTableExcludedColumns() {
        return new SchemaMapping.Sybase.Databases.Database.Tables.Table.ExcludedColumns();
    }

    /**
     * Create an instance of {@link SchemaMapping.Sybase.Databases.Database.Tables.Table.AffinityKey }
     * 
     */
    public SchemaMapping.Sybase.Databases.Database.Tables.Table.AffinityKey createSchemaMappingSybaseDatabasesDatabaseTablesTableAffinityKey() {
        return new SchemaMapping.Sybase.Databases.Database.Tables.Table.AffinityKey();
    }

}
