//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 10:39:34 AM PST 
//


package com.aladdin.sybase.schema.mapper.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sybase">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="databases">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="database" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;choice>
 *                                       &lt;element name="tables">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="table" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;choice>
 *                                                           &lt;element name="excluded-columns" minOccurs="0">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
 *                                                                   &lt;/sequence>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                           &lt;element name="affinity-key" minOccurs="0">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;sequence>
 *                                                                     &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
 *                                                                   &lt;/sequence>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/choice>
 *                                                         &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="pk-index-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="class-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="cache-mode" default="REPLICATED">
 *                                                           &lt;simpleType>
 *                                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                                               &lt;enumeration value="PARTITIONED"/>
 *                                                               &lt;enumeration value="REPLICATED"/>
 *                                                             &lt;/restriction>
 *                                                           &lt;/simpleType>
 *                                                         &lt;/attribute>
 *                                                         &lt;attribute name="write-synch-mode" default="FULL_ASYNC">
 *                                                           &lt;simpleType>
 *                                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                                               &lt;enumeration value="FULL_SYNC"/>
 *                                                               &lt;enumeration value="PRIMARY_SYNC"/>
 *                                                               &lt;enumeration value="FULL_ASYNC"/>
 *                                                             &lt;/restriction>
 *                                                           &lt;/simpleType>
 *                                                         &lt;/attribute>
 *                                                         &lt;attribute name="rebal-mode" default="ASYNC">
 *                                                           &lt;simpleType>
 *                                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                                               &lt;enumeration value="SYNC"/>
 *                                                               &lt;enumeration value="ASYNC"/>
 *                                                               &lt;enumeration value="NONE"/>
 *                                                             &lt;/restriction>
 *                                                           &lt;/simpleType>
 *                                                         &lt;/attribute>
 *                                                         &lt;attribute name="backups" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                                                         &lt;attribute name="cache-atomicity-mode" default="TRANSACTIONAL">
 *                                                           &lt;simpleType>
 *                                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                                               &lt;enumeration value="ATOMIC"/>
 *                                                               &lt;enumeration value="TRANSACTIONAL"/>
 *                                                             &lt;/restriction>
 *                                                           &lt;/simpleType>
 *                                                         &lt;/attribute>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="map-all" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/choice>
 *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sybase"
})
@XmlRootElement(name = "schema-mapping")
public class SchemaMapping {

    @XmlElement(required = true)
    protected SchemaMapping.Sybase sybase;

    /**
     * Gets the value of the sybase property.
     * 
     * @return
     *     possible object is
     *     {@link SchemaMapping.Sybase }
     *     
     */
    public SchemaMapping.Sybase getSybase() {
        return sybase;
    }

    /**
     * Sets the value of the sybase property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchemaMapping.Sybase }
     *     
     */
    public void setSybase(SchemaMapping.Sybase value) {
        this.sybase = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="databases">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="database" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;choice>
     *                             &lt;element name="tables">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="table" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;choice>
     *                                                 &lt;element name="excluded-columns" minOccurs="0">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
     *                                                         &lt;/sequence>
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                                 &lt;element name="affinity-key" minOccurs="0">
     *                                                   &lt;complexType>
     *                                                     &lt;complexContent>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                         &lt;sequence>
     *                                                           &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
     *                                                         &lt;/sequence>
     *                                                       &lt;/restriction>
     *                                                     &lt;/complexContent>
     *                                                   &lt;/complexType>
     *                                                 &lt;/element>
     *                                               &lt;/choice>
     *                                               &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="pk-index-name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="class-name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                               &lt;attribute name="cache-mode" default="REPLICATED">
     *                                                 &lt;simpleType>
     *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                                                     &lt;enumeration value="PARTITIONED"/>
     *                                                     &lt;enumeration value="REPLICATED"/>
     *                                                   &lt;/restriction>
     *                                                 &lt;/simpleType>
     *                                               &lt;/attribute>
     *                                               &lt;attribute name="write-synch-mode" default="FULL_ASYNC">
     *                                                 &lt;simpleType>
     *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                                                     &lt;enumeration value="FULL_SYNC"/>
     *                                                     &lt;enumeration value="PRIMARY_SYNC"/>
     *                                                     &lt;enumeration value="FULL_ASYNC"/>
     *                                                   &lt;/restriction>
     *                                                 &lt;/simpleType>
     *                                               &lt;/attribute>
     *                                               &lt;attribute name="rebal-mode" default="ASYNC">
     *                                                 &lt;simpleType>
     *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                                                     &lt;enumeration value="SYNC"/>
     *                                                     &lt;enumeration value="ASYNC"/>
     *                                                     &lt;enumeration value="NONE"/>
     *                                                   &lt;/restriction>
     *                                                 &lt;/simpleType>
     *                                               &lt;/attribute>
     *                                               &lt;attribute name="backups" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *                                               &lt;attribute name="cache-atomicity-mode" default="TRANSACTIONAL">
     *                                                 &lt;simpleType>
     *                                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                                                     &lt;enumeration value="ATOMIC"/>
     *                                                     &lt;enumeration value="TRANSACTIONAL"/>
     *                                                   &lt;/restriction>
     *                                                 &lt;/simpleType>
     *                                               &lt;/attribute>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="map-all" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/choice>
     *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "databases"
    })
    public static class Sybase {

        @XmlElement(required = true)
        protected SchemaMapping.Sybase.Databases databases;

        /**
         * Gets the value of the databases property.
         * 
         * @return
         *     possible object is
         *     {@link SchemaMapping.Sybase.Databases }
         *     
         */
        public SchemaMapping.Sybase.Databases getDatabases() {
            return databases;
        }

        /**
         * Sets the value of the databases property.
         * 
         * @param value
         *     allowed object is
         *     {@link SchemaMapping.Sybase.Databases }
         *     
         */
        public void setDatabases(SchemaMapping.Sybase.Databases value) {
            this.databases = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="database" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;choice>
         *                   &lt;element name="tables">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="table" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;choice>
         *                                       &lt;element name="excluded-columns" minOccurs="0">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
         *                                               &lt;/sequence>
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                       &lt;element name="affinity-key" minOccurs="0">
         *                                         &lt;complexType>
         *                                           &lt;complexContent>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                               &lt;sequence>
         *                                                 &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
         *                                               &lt;/sequence>
         *                                             &lt;/restriction>
         *                                           &lt;/complexContent>
         *                                         &lt;/complexType>
         *                                       &lt;/element>
         *                                     &lt;/choice>
         *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="pk-index-name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="class-name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                     &lt;attribute name="cache-mode" default="REPLICATED">
         *                                       &lt;simpleType>
         *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *                                           &lt;enumeration value="PARTITIONED"/>
         *                                           &lt;enumeration value="REPLICATED"/>
         *                                         &lt;/restriction>
         *                                       &lt;/simpleType>
         *                                     &lt;/attribute>
         *                                     &lt;attribute name="write-synch-mode" default="FULL_ASYNC">
         *                                       &lt;simpleType>
         *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *                                           &lt;enumeration value="FULL_SYNC"/>
         *                                           &lt;enumeration value="PRIMARY_SYNC"/>
         *                                           &lt;enumeration value="FULL_ASYNC"/>
         *                                         &lt;/restriction>
         *                                       &lt;/simpleType>
         *                                     &lt;/attribute>
         *                                     &lt;attribute name="rebal-mode" default="ASYNC">
         *                                       &lt;simpleType>
         *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *                                           &lt;enumeration value="SYNC"/>
         *                                           &lt;enumeration value="ASYNC"/>
         *                                           &lt;enumeration value="NONE"/>
         *                                         &lt;/restriction>
         *                                       &lt;/simpleType>
         *                                     &lt;/attribute>
         *                                     &lt;attribute name="backups" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
         *                                     &lt;attribute name="cache-atomicity-mode" default="TRANSACTIONAL">
         *                                       &lt;simpleType>
         *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *                                           &lt;enumeration value="ATOMIC"/>
         *                                           &lt;enumeration value="TRANSACTIONAL"/>
         *                                         &lt;/restriction>
         *                                       &lt;/simpleType>
         *                                     &lt;/attribute>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="map-all" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/choice>
         *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "database"
        })
        public static class Databases {

            @XmlElement(required = true)
            protected List<SchemaMapping.Sybase.Databases.Database> database;

            /**
             * Gets the value of the database property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the database property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDatabase().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SchemaMapping.Sybase.Databases.Database }
             * 
             * 
             */
            public List<SchemaMapping.Sybase.Databases.Database> getDatabase() {
                if (database == null) {
                    database = new ArrayList<SchemaMapping.Sybase.Databases.Database>();
                }
                return this.database;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice>
             *         &lt;element name="tables">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="table" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;choice>
             *                             &lt;element name="excluded-columns" minOccurs="0">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
             *                                     &lt;/sequence>
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                             &lt;element name="affinity-key" minOccurs="0">
             *                               &lt;complexType>
             *                                 &lt;complexContent>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                                     &lt;sequence>
             *                                       &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
             *                                     &lt;/sequence>
             *                                   &lt;/restriction>
             *                                 &lt;/complexContent>
             *                               &lt;/complexType>
             *                             &lt;/element>
             *                           &lt;/choice>
             *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="pk-index-name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="class-name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                           &lt;attribute name="cache-mode" default="REPLICATED">
             *                             &lt;simpleType>
             *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
             *                                 &lt;enumeration value="PARTITIONED"/>
             *                                 &lt;enumeration value="REPLICATED"/>
             *                               &lt;/restriction>
             *                             &lt;/simpleType>
             *                           &lt;/attribute>
             *                           &lt;attribute name="write-synch-mode" default="FULL_ASYNC">
             *                             &lt;simpleType>
             *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
             *                                 &lt;enumeration value="FULL_SYNC"/>
             *                                 &lt;enumeration value="PRIMARY_SYNC"/>
             *                                 &lt;enumeration value="FULL_ASYNC"/>
             *                               &lt;/restriction>
             *                             &lt;/simpleType>
             *                           &lt;/attribute>
             *                           &lt;attribute name="rebal-mode" default="ASYNC">
             *                             &lt;simpleType>
             *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
             *                                 &lt;enumeration value="SYNC"/>
             *                                 &lt;enumeration value="ASYNC"/>
             *                                 &lt;enumeration value="NONE"/>
             *                               &lt;/restriction>
             *                             &lt;/simpleType>
             *                           &lt;/attribute>
             *                           &lt;attribute name="backups" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
             *                           &lt;attribute name="cache-atomicity-mode" default="TRANSACTIONAL">
             *                             &lt;simpleType>
             *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
             *                                 &lt;enumeration value="ATOMIC"/>
             *                                 &lt;enumeration value="TRANSACTIONAL"/>
             *                               &lt;/restriction>
             *                             &lt;/simpleType>
             *                           &lt;/attribute>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="map-all" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/choice>
             *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tables"
            })
            public static class Database {

                protected SchemaMapping.Sybase.Databases.Database.Tables tables;
                @XmlAttribute(name = "name", required = true)
                protected String name;

                /**
                 * Gets the value of the tables property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link SchemaMapping.Sybase.Databases.Database.Tables }
                 *     
                 */
                public SchemaMapping.Sybase.Databases.Database.Tables getTables() {
                    return tables;
                }

                /**
                 * Sets the value of the tables property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link SchemaMapping.Sybase.Databases.Database.Tables }
                 *     
                 */
                public void setTables(SchemaMapping.Sybase.Databases.Database.Tables value) {
                    this.tables = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="table" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;choice>
                 *                   &lt;element name="excluded-columns" minOccurs="0">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
                 *                           &lt;/sequence>
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                   &lt;element name="affinity-key" minOccurs="0">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;sequence>
                 *                             &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
                 *                           &lt;/sequence>
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/choice>
                 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="pk-index-name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="class-name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                 &lt;attribute name="cache-mode" default="REPLICATED">
                 *                   &lt;simpleType>
                 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
                 *                       &lt;enumeration value="PARTITIONED"/>
                 *                       &lt;enumeration value="REPLICATED"/>
                 *                     &lt;/restriction>
                 *                   &lt;/simpleType>
                 *                 &lt;/attribute>
                 *                 &lt;attribute name="write-synch-mode" default="FULL_ASYNC">
                 *                   &lt;simpleType>
                 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
                 *                       &lt;enumeration value="FULL_SYNC"/>
                 *                       &lt;enumeration value="PRIMARY_SYNC"/>
                 *                       &lt;enumeration value="FULL_ASYNC"/>
                 *                     &lt;/restriction>
                 *                   &lt;/simpleType>
                 *                 &lt;/attribute>
                 *                 &lt;attribute name="rebal-mode" default="ASYNC">
                 *                   &lt;simpleType>
                 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
                 *                       &lt;enumeration value="SYNC"/>
                 *                       &lt;enumeration value="ASYNC"/>
                 *                       &lt;enumeration value="NONE"/>
                 *                     &lt;/restriction>
                 *                   &lt;/simpleType>
                 *                 &lt;/attribute>
                 *                 &lt;attribute name="backups" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
                 *                 &lt;attribute name="cache-atomicity-mode" default="TRANSACTIONAL">
                 *                   &lt;simpleType>
                 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
                 *                       &lt;enumeration value="ATOMIC"/>
                 *                       &lt;enumeration value="TRANSACTIONAL"/>
                 *                     &lt;/restriction>
                 *                   &lt;/simpleType>
                 *                 &lt;/attribute>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="map-all" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "table"
                })
                public static class Tables {

                    protected List<SchemaMapping.Sybase.Databases.Database.Tables.Table> table;
                    @XmlAttribute(name = "map-all")
                    protected Boolean mapAll;

                    /**
                     * Gets the value of the table property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the table property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getTable().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link SchemaMapping.Sybase.Databases.Database.Tables.Table }
                     * 
                     * 
                     */
                    public List<SchemaMapping.Sybase.Databases.Database.Tables.Table> getTable() {
                        if (table == null) {
                            table = new ArrayList<SchemaMapping.Sybase.Databases.Database.Tables.Table>();
                        }
                        return this.table;
                    }

                    /**
                     * Gets the value of the mapAll property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Boolean }
                     *     
                     */
                    public boolean isMapAll() {
                        if (mapAll == null) {
                            return false;
                        } else {
                            return mapAll;
                        }
                    }

                    /**
                     * Sets the value of the mapAll property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Boolean }
                     *     
                     */
                    public void setMapAll(Boolean value) {
                        this.mapAll = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;choice>
                     *         &lt;element name="excluded-columns" minOccurs="0">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
                     *                 &lt;/sequence>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *         &lt;element name="affinity-key" minOccurs="0">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
                     *                 &lt;/sequence>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *       &lt;/choice>
                     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="pk-index-name" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="class-name" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *       &lt;attribute name="cache-mode" default="REPLICATED">
                     *         &lt;simpleType>
                     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
                     *             &lt;enumeration value="PARTITIONED"/>
                     *             &lt;enumeration value="REPLICATED"/>
                     *           &lt;/restriction>
                     *         &lt;/simpleType>
                     *       &lt;/attribute>
                     *       &lt;attribute name="write-synch-mode" default="FULL_ASYNC">
                     *         &lt;simpleType>
                     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
                     *             &lt;enumeration value="FULL_SYNC"/>
                     *             &lt;enumeration value="PRIMARY_SYNC"/>
                     *             &lt;enumeration value="FULL_ASYNC"/>
                     *           &lt;/restriction>
                     *         &lt;/simpleType>
                     *       &lt;/attribute>
                     *       &lt;attribute name="rebal-mode" default="ASYNC">
                     *         &lt;simpleType>
                     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
                     *             &lt;enumeration value="SYNC"/>
                     *             &lt;enumeration value="ASYNC"/>
                     *             &lt;enumeration value="NONE"/>
                     *           &lt;/restriction>
                     *         &lt;/simpleType>
                     *       &lt;/attribute>
                     *       &lt;attribute name="backups" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
                     *       &lt;attribute name="cache-atomicity-mode" default="TRANSACTIONAL">
                     *         &lt;simpleType>
                     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
                     *             &lt;enumeration value="ATOMIC"/>
                     *             &lt;enumeration value="TRANSACTIONAL"/>
                     *           &lt;/restriction>
                     *         &lt;/simpleType>
                     *       &lt;/attribute>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "excludedColumns",
                        "affinityKey"
                    })
                    public static class Table {

                        @XmlElement(name = "excluded-columns")
                        protected SchemaMapping.Sybase.Databases.Database.Tables.Table.ExcludedColumns excludedColumns;
                        @XmlElement(name = "affinity-key")
                        protected SchemaMapping.Sybase.Databases.Database.Tables.Table.AffinityKey affinityKey;
                        @XmlAttribute(name = "name", required = true)
                        protected String name;
                        @XmlAttribute(name = "pk-index-name")
                        protected String pkIndexName;
                        @XmlAttribute(name = "class-name")
                        protected String className;
                        @XmlAttribute(name = "cache-mode")
                        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                        protected String cacheMode;
                        @XmlAttribute(name = "write-synch-mode")
                        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                        protected String writeSynchMode;
                        @XmlAttribute(name = "rebal-mode")
                        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                        protected String rebalMode;
                        @XmlAttribute(name = "backups")
                        protected Integer backups;
                        @XmlAttribute(name = "cache-atomicity-mode")
                        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                        protected String cacheAtomicityMode;

                        /**
                         * Gets the value of the excludedColumns property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link SchemaMapping.Sybase.Databases.Database.Tables.Table.ExcludedColumns }
                         *     
                         */
                        public SchemaMapping.Sybase.Databases.Database.Tables.Table.ExcludedColumns getExcludedColumns() {
                            return excludedColumns;
                        }

                        /**
                         * Sets the value of the excludedColumns property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link SchemaMapping.Sybase.Databases.Database.Tables.Table.ExcludedColumns }
                         *     
                         */
                        public void setExcludedColumns(SchemaMapping.Sybase.Databases.Database.Tables.Table.ExcludedColumns value) {
                            this.excludedColumns = value;
                        }

                        /**
                         * Gets the value of the affinityKey property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link SchemaMapping.Sybase.Databases.Database.Tables.Table.AffinityKey }
                         *     
                         */
                        public SchemaMapping.Sybase.Databases.Database.Tables.Table.AffinityKey getAffinityKey() {
                            return affinityKey;
                        }

                        /**
                         * Sets the value of the affinityKey property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link SchemaMapping.Sybase.Databases.Database.Tables.Table.AffinityKey }
                         *     
                         */
                        public void setAffinityKey(SchemaMapping.Sybase.Databases.Database.Tables.Table.AffinityKey value) {
                            this.affinityKey = value;
                        }

                        /**
                         * Gets the value of the name property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                        /**
                         * Gets the value of the pkIndexName property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPkIndexName() {
                            return pkIndexName;
                        }

                        /**
                         * Sets the value of the pkIndexName property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setPkIndexName(String value) {
                            this.pkIndexName = value;
                        }

                        /**
                         * Gets the value of the className property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getClassName() {
                            return className;
                        }

                        /**
                         * Sets the value of the className property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setClassName(String value) {
                            this.className = value;
                        }

                        /**
                         * Gets the value of the cacheMode property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getCacheMode() {
                            if (cacheMode == null) {
                                return "REPLICATED";
                            } else {
                                return cacheMode;
                            }
                        }

                        /**
                         * Sets the value of the cacheMode property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setCacheMode(String value) {
                            this.cacheMode = value;
                        }

                        /**
                         * Gets the value of the writeSynchMode property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getWriteSynchMode() {
                            if (writeSynchMode == null) {
                                return "FULL_ASYNC";
                            } else {
                                return writeSynchMode;
                            }
                        }

                        /**
                         * Sets the value of the writeSynchMode property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setWriteSynchMode(String value) {
                            this.writeSynchMode = value;
                        }

                        /**
                         * Gets the value of the rebalMode property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getRebalMode() {
                            if (rebalMode == null) {
                                return "ASYNC";
                            } else {
                                return rebalMode;
                            }
                        }

                        /**
                         * Sets the value of the rebalMode property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setRebalMode(String value) {
                            this.rebalMode = value;
                        }

                        /**
                         * Gets the value of the backups property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Integer }
                         *     
                         */
                        public int getBackups() {
                            if (backups == null) {
                                return  0;
                            } else {
                                return backups;
                            }
                        }

                        /**
                         * Sets the value of the backups property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Integer }
                         *     
                         */
                        public void setBackups(Integer value) {
                            this.backups = value;
                        }

                        /**
                         * Gets the value of the cacheAtomicityMode property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getCacheAtomicityMode() {
                            if (cacheAtomicityMode == null) {
                                return "TRANSACTIONAL";
                            } else {
                                return cacheAtomicityMode;
                            }
                        }

                        /**
                         * Sets the value of the cacheAtomicityMode property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setCacheAtomicityMode(String value) {
                            this.cacheAtomicityMode = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
                         *       &lt;/sequence>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "column"
                        })
                        public static class AffinityKey {

                            @XmlElement(required = true)
                            protected List<Column> column;

                            /**
                             * Gets the value of the column property.
                             * 
                             * <p>
                             * This accessor method returns a reference to the live list,
                             * not a snapshot. Therefore any modification you make to the
                             * returned list will be present inside the JAXB object.
                             * This is why there is not a <CODE>set</CODE> method for the column property.
                             * 
                             * <p>
                             * For example, to add a new item, do as follows:
                             * <pre>
                             *    getColumn().add(newItem);
                             * </pre>
                             * 
                             * 
                             * <p>
                             * Objects of the following type(s) are allowed in the list
                             * {@link Column }
                             * 
                             * 
                             */
                            public List<Column> getColumn() {
                                if (column == null) {
                                    column = new ArrayList<Column>();
                                }
                                return this.column;
                            }

                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="column" type="{}column" maxOccurs="unbounded"/>
                         *       &lt;/sequence>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "column"
                        })
                        public static class ExcludedColumns {

                            @XmlElement(required = true)
                            protected List<Column> column;

                            /**
                             * Gets the value of the column property.
                             * 
                             * <p>
                             * This accessor method returns a reference to the live list,
                             * not a snapshot. Therefore any modification you make to the
                             * returned list will be present inside the JAXB object.
                             * This is why there is not a <CODE>set</CODE> method for the column property.
                             * 
                             * <p>
                             * For example, to add a new item, do as follows:
                             * <pre>
                             *    getColumn().add(newItem);
                             * </pre>
                             * 
                             * 
                             * <p>
                             * Objects of the following type(s) are allowed in the list
                             * {@link Column }
                             * 
                             * 
                             */
                            public List<Column> getColumn() {
                                if (column == null) {
                                    column = new ArrayList<Column>();
                                }
                                return this.column;
                            }

                        }

                    }

                }

            }

        }

    }

}
